/*
 * File: app/store/EquipmentWithUsers.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.store.EquipmentWithUsers', {
    extend: 'Ext.data.Store',
    alias: 'store.equipmentwithusers',

    requires: [
        'smart.model.EquipmentWithUser',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'smart.model.EquipmentWithUser',
            storeId: 'EquipmentWithUsers',
            data: [
                {
                    id: 28,
                    name: 'ver'
                },
                {
                    id: 14,
                    name: 'ali'
                },
                {
                    id: 47,
                    name: 'amet'
                },
                {
                    id: 58,
                    name: 'id'
                },
                {
                    id: 57,
                    name: 'laud'
                },
                {
                    id: 69,
                    name: 'quib'
                }
            ],
            proxy: {
                type: 'ajax',
                url: 'EquipmentUserAction',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});