/*
 * File: app/view/AddNewEquipment.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.AddNewEquipment', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    width: 484,
    resizable: false,
    title: '添加新设备',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    url: 'AddNewEquipmentAction',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            width: 300,
                            fieldLabel: 'MAC',
                            name: 'mac'
                        },
                        {
                            xtype: 'combobox',
                            flex: 1,
                            width: 300,
                            fieldLabel: '类型',
                            name: 'type'
                        },
                        {
                            xtype: 'textfield',
                            width: 300,
                            fieldLabel: '描述',
                            name: 'description'
                        },
                        {
                            xtype: 'textfield',
                            width: 300,
                            fieldLabel: '厂商'
                        },
                        {
                            xtype: 'textfield',
                            width: 300,
                            fieldLabel: 'Label',
                            name: '其他1'
                        },
                        {
                            xtype: 'textfield',
                            width: 300,
                            fieldLabel: 'Label',
                            name: '其他2'
                        },
                        {
                            xtype: 'textareafield',
                            height: 105,
                            width: 300,
                            fieldLabel: 'Label',
                            name: 'more'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'CanfirmEquipmentAdd',
                                    text: '确认'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'CancenEquipmentAdd',
                                    text: '取消'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});