/*
 * File: app/view/AddNewUser.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.AddNewUser', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 283,
    width: 354,
    resizable: false,
    title: '添加新用户',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: '10 40 10 0',
                    header: false,
                    title: 'My Form',
                    url: 'AddNewUserAction',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            width: 250,
                            fieldLabel: '名称',
                            labelAlign: 'right',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            width: 250,
                            fieldLabel: '密码',
                            labelAlign: 'right',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            width: 250,
                            fieldLabel: 'Tel',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            width: 250,
                            fieldLabel: 'Email',
                            labelAlign: 'right',
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            width: 250,
                            fieldLabel: '家庭代码',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'filefield',
                            width: 250,
                            fieldLabel: '上传头像',
                            labelAlign: 'right',
                            buttonMargin: 0,
                            buttonText: '选择'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    itemId: 'ConfirmUserAdd',
                                    text: '确认添加'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'CancenUserAdd',
                                    text: '取消添加'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});