/*
 * File: app/view/AddNews.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.AddNews', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    autoShow: true,
    height: 530,
    width: 773,
    title: '添加新通知',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    url: 'AddNoticeAction',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 385,
                            fieldLabel: '标题',
                            labelAlign: 'right',
                            labelWidth: 80,
                            name: 'title'
                        },
                        {
                            xtype: 'htmleditor',
                            height: 385,
                            width: 700,
                            fieldLabel: '内容',
                            labelAlign: 'right',
                            labelWidth: 80,
                            name: 'content'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'SubmitAddNews',
                                    width: 100,
                                    text: '提交'
                                },
                                {
                                    xtype: 'button',
                                    id: 'QuitAddNews',
                                    width: 100,
                                    text: '关闭'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});