/*
 * File: app/view/First.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.First', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.panel.Tool',
        'Ext.toolbar.Paging'
    ],

    width: 810,
    layout: 'anchor',
    title: '首页',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 192,
                    itemId: 'MgrFrom',
                    padding: '10 0 0 10',
                    header: false,
                    manageHeight: false,
                    title: 'My Form',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: '100%',
                            title: '管理员信息',
                            layout: {
                                type: 'table',
                                columns: 2
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: '编号',
                                    labelWidth: 50,
                                    name: 'num',
                                    value: '001'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: 'ID',
                                    labelWidth: 50,
                                    name: 'id',
                                    value: '201455445'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: '昵称',
                                    labelWidth: 50,
                                    name: 'nickname',
                                    value: '小者'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: '级别',
                                    labelWidth: 50,
                                    name: 'type',
                                    value: '普通管理员'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: '姓名',
                                    labelWidth: 50,
                                    name: 'name',
                                    value: '杨同学'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: 'Email',
                                    labelWidth: 50,
                                    name: 'email',
                                    value: 'yang@edu.hust.Com'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: '电话',
                                    labelWidth: 50,
                                    name: 'tel',
                                    value: '13700000254'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 4',
                                    fieldLabel: 'IP',
                                    labelWidth: 50,
                                    name: 'ip',
                                    value: '218.199.81.152'
                                },
                                {
                                    xtype: 'displayfield',
                                    colspan: 2,
                                    margin: '0 4',
                                    style: 'border:1px solid #ccc',
                                    fieldLabel: '上次登录信息',
                                    labelWidth: 90,
                                    name: 'updatetime',
                                    value: '2015-12-15 14:23 IP:218.199.11.180'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            title: '系统服务信息',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    value: '运行状态'
                                },
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    value: '系统告警'
                                },
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    value: '设备告警'
                                },
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    value: '日志告警'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'left',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'EditeMgrInfo',
                                    margin: '4 0',
                                    menuAlign: 'r-br',
                                    text: '修改管理员信息'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'ListMgrs',
                                    menuAlign: 'r',
                                    text: '查看所有管理员'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    anchor: '0 70%',
                    header: false,
                    manageHeight: false,
                    title: '系统通知',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: '100%',
                            id: 'NoticeGrid',
                            manageHeight: false,
                            title: ' 系统通知',
                            sortableColumns: false,
                            store: 'NoticeModels',
                            viewConfig: {
                                overflowX: 'scroll',
                                overflowY: 'scroll'
                            },
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    width: 100,
                                    dataIndex: 'id',
                                    text: 'ID',
                                    format: '0,000'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'type',
                                    text: '类型'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '80%',
                                    dataIndex: 'title',
                                    text: '标题',
                                    flex: 1
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: '日期',
                                    format: 'Y-j-m'
                                }
                            ],
                            tools: [
                                {
                                    xtype: 'tool',
                                    callback: function(owner, tool, event) {
                                        var addnews=Ext.create('smart.view.AddNews');
                                        addnews.show();
                                    },
                                    itemId: 'Add',
                                    type: 'plus'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'NoticeModels'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});