/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.Login', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    autoShow: true,
    height: 316,
    id: 'LoginWindow',
    padding: '',
    width: 585,
    layout: 'fit',
    closable: false,
    title: '登录',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'myform',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    url: 'json/form.asp',
                    waitMsgTarget: true,
                    waitTitle: '登录中....',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            margins: '10',
                            width: '',
                            fieldLabel: '帐 号',
                            labelAlign: 'right',
                            labelWidth: 50,
                            allowBlank: false,
                            blankText: '请输入你的ID',
                            emptyText: 'Your ID'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '密 码',
                            labelAlign: 'right',
                            labelWidth: 50,
                            allowBlank: false,
                            blankText: '请输入你的密码',
                            emptyText: 'Your Password'
                        },
                        {
                            xtype: 'button',
                            margins: '10',
                            formBind: true,
                            height: 34,
                            id: 'LoginBtn',
                            width: 150,
                            text: '登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});