/*
 * File: app/view/Sever.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.Sever', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.chart.Chart',
        'Ext.util.Point',
        'Ext.chart.series.Pie',
        'Ext.chart.Legend',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.chart.axis.Category',
        'Ext.chart.series.Line',
        'Ext.chart.axis.Radial',
        'Ext.chart.series.Radar',
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    height: 521,
    width: 1078,
    layout: 'fit',
    header: false,
    title: '服务器运行',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    height: '100%',
                    manageHeight: false,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            manageHeight: false,
                            title: '服务器信息',
                            tabConfig: {
                                xtype: 'tab',
                                width: 120,
                                closable: false
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    frame: true,
                                    height: 200,
                                    itemId: 'SeverInfo',
                                    overflowY: 'auto',
                                    bodyPadding: 10,
                                    header: false,
                                    manageHeight: false,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: '系统基本信息',
                                            layout: {
                                                type: 'table',
                                                columns: 3
                                            },
                                            items: [
                                                {
                                                    xtype: 'displayfield',
                                                    style: '{\n    color;\'#006699\'\n}',
                                                    hideLabel: true,
                                                    labelAlign: 'right',
                                                    value: '智慧家居运维客户端系统',
                                                    fieldStyle: 'color:#006699;font-size:16px;'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '系统版本',
                                                    labelAlign: 'right',
                                                    name: 'systemversion',
                                                    value: '3.0.1'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '更新时间',
                                                    labelAlign: 'right',
                                                    name: 'update',
                                                    value: '2016-4-20 18:21'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: 'JBoss版本',
                                                    labelAlign: 'right',
                                                    name: 'jbossversion',
                                                    value: 'Jboss 7.0.1'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    colspan: 2,
                                                    fieldLabel: 'JDK版本',
                                                    labelAlign: 'right',
                                                    name: 'jdkversion',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '操作系统',
                                                    labelAlign: 'right',
                                                    name: 'osversion',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '内存容量',
                                                    labelAlign: 'right',
                                                    name: 'memery',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '硬盘容量',
                                                    labelAlign: 'right',
                                                    name: 'disk',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '服务器线程数',
                                                    labelAlign: 'right',
                                                    name: 'threads',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '服务器节点',
                                                    labelAlign: 'right',
                                                    name: 'clusterbodes',
                                                    value: 'Display Field'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: 'column',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: '100%',
                                            manageHeight: false,
                                            title: '',
                                            items: [
                                                {
                                                    xtype: 'chart',
                                                    height: 250,
                                                    width: 400,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'SeverMemoryModels',
                                                    series: [
                                                        {
                                                            type: 'pie',
                                                            highlight: {
                                                                segment: {
                                                                    margin: 20
                                                                }
                                                            },
                                                            label: {
                                                                field: [
                                                                    'name'
                                                                ],
                                                                display: 'rotate',
                                                                contrast: true,
                                                                font: '12px Arial'
                                                            },
                                                            showInLegend: true,
                                                            angleField: 'memory',
                                                            donut: 20
                                                        }
                                                    ],
                                                    legend: {
                                                        position: 'left'
                                                    }
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    layout: {
                                                        type: 'hbox',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: '服务器内存消耗分布：'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            columnWidth: '',
                                            height: '100%',
                                            manageHeight: false,
                                            title: '',
                                            items: [
                                                {
                                                    xtype: 'chart',
                                                    height: 250,
                                                    width: 618,
                                                    shadow: false,
                                                    animate: true,
                                                    insetPadding: 20,
                                                    store: 'SeverHttpRequestModels',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'time'
                                                            ],
                                                            title: 'Time',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            grid: true,
                                                            title: '连接数',
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            highlight: {
                                                                size: 7,
                                                                radius: 7
                                                            },
                                                            title: 'Session',
                                                            xField: 'time',
                                                            yField: 'Session',
                                                            smooth: 3
                                                        },
                                                        {
                                                            type: 'line',
                                                            highlight: {
                                                                size: 7,
                                                                radius: 7
                                                            },
                                                            title: 'HttpRequest',
                                                            xField: 'time',
                                                            yField: 'HttpRequest',
                                                            smooth: 3,
                                                            style: {
                                                                lineColor: 0xFF0033,
                                                                borderColor: 0xFF0033
                                                            }
                                                        }
                                                    ],
                                                    legend: {

                                                    }
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    layout: {
                                                        type: 'hbox',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: '服务器Http请求和Session连接'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            manageHeight: false,
                            title: '集群运行',
                            tabConfig: {
                                xtype: 'tab',
                                width: 120,
                                closable: false
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    frame: true,
                                    height: 200,
                                    itemId: 'SeverClusterInfo',
                                    overflowY: 'auto',
                                    bodyPadding: 10,
                                    header: false,
                                    manageHeight: false,
                                    url: 'SeverClusterInfoAction',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: '集群描述',
                                            layout: {
                                                type: 'table',
                                                columns: 3
                                            },
                                            items: [
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '集群节点',
                                                    labelAlign: 'right'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '均衡器',
                                                    labelAlign: 'right',
                                                    name: 'systemversion',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: '占比',
                                                    labelAlign: 'right',
                                                    name: 'update',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: 'A节点',
                                                    labelAlign: 'right',
                                                    name: 'jbossversion',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: 'B节点',
                                                    labelAlign: 'right',
                                                    name: 'jdkversion',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: 'C节点',
                                                    labelAlign: 'right',
                                                    name: 'osversion',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: 'D节点',
                                                    labelAlign: 'right',
                                                    name: 'memery',
                                                    value: 'Display Field'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    fieldLabel: 'F节点',
                                                    labelAlign: 'right',
                                                    name: 'disk',
                                                    value: 'Display Field'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    header: false,
                                    title: 'My Panel',
                                    items: [
                                        {
                                            xtype: 'chart',
                                            height: 250,
                                            width: 400,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'SeverClusterModels',
                                            theme: 'Category2',
                                            axes: [
                                                {
                                                    type: 'Radial',
                                                    steps: 4,
                                                    position: 'radial'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'radar',
                                                    highlight: {
                                                        size: 7,
                                                        radius: 7
                                                    },
                                                    showInLegend: true,
                                                    title: '集群节点',
                                                    showMarkers: true,
                                                    style: {
                                                        opacity: 0.4
                                                    },
                                                    xField: 'id',
                                                    yField: 'business'
                                                }
                                            ],
                                            legend: {
                                                position: 'left'
                                            }
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            layout: {
                                                type: 'hbox',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: '集群节点消耗分布'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            manageHeight: false,
                            title: '运行日志',
                            tabConfig: {
                                xtype: 'tab',
                                width: 120
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    border: '1 solid #FF0000',
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '开启接收'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '停止接收'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '清除'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'dataview',
                                    height: '100%',
                                    id: 'RuningLog',
                                    padding: '0 4',
                                    overflowY: 'auto',
                                    itemSelector: 'div',
                                    itemTpl: [
                                        '<span style=\'color:#3333cc\'>{time}:{title}</span></br>【info】:{description}</br>--'
                                    ],
                                    store: 'SeverRuningLogs'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            manageHeight: false,
                            title: 'Out输出',
                            tabConfig: {
                                xtype: 'tab',
                                width: 120
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    border: '1 solid #FF0000',
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '开启接收'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '停止接收'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '清除'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'dataview',
                                    height: '100%',
                                    id: 'RuningLog2',
                                    padding: '0 4',
                                    overflowY: 'auto',
                                    itemSelector: 'div',
                                    itemTpl: [
                                        '<span style=\'color:#00cc00\'>{time}:{title}</span></br>【Out-info】:{description}</br>--'
                                    ],
                                    store: 'SeverOutLog'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            manageHeight: false,
                            title: 'Error输出',
                            tabConfig: {
                                xtype: 'tab',
                                width: 120,
                                closable: false
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    border: '1 solid #FF0000',
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '开启接收'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '停止接收'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 100,
                                            text: '清除'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'dataview',
                                    height: '100%',
                                    id: 'RuningLog1',
                                    padding: '0 4',
                                    overflowY: 'auto',
                                    itemSelector: 'div',
                                    itemTpl: [
                                        '<span style=\'color:#ff0000\'>{time}:{title}</span></br>【Error-info】:{description}</br>--'
                                    ],
                                    store: 'SeverErrorLog'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});