/*
 * File: app/view/UserDetail.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.UserDetail', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.Img',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.selection.RowModel'
    ],

    autoShow: true,
    height: 571,
    itemId: 'mywindow',
    width: 754,
    title: '用户详细信息',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'Uform',
                    bodyPadding: '0 10',
                    header: false,
                    manageHeight: false,
                    title: 'My Form',
                    url: 'EditeUserAction',
                    layout: {
                        type: 'table',
                        columns: 5
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'EditUserInfobtn',
                                    text: '修改个人信息'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'SubmitUserEditbtn',
                                    text: '提交修改'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'EditSelectEquipmentbtn',
                                    text: '编辑选中设备'
                                },
                                {
                                    xtype: 'button',
                                    id: 'DeleteSelectEquipmentbtn',
                                    text: '删除选中设备'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'AddNewEquipment',
                                    text: '添加新设备'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'image',
                            colspan: 3,
                            rowspan: 3,
                            height: 100,
                            width: 100,
                            src: 'images/photo.jpg'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '名称',
                            labelAlign: 'right',
                            labelWidth: 50,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '密码',
                            labelAlign: 'right',
                            labelWidth: 50,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Label',
                            labelAlign: 'right',
                            labelWidth: 50,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Label',
                            labelAlign: 'right',
                            labelWidth: 50,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Email',
                            labelAlign: 'right',
                            labelWidth: 50,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Tel',
                            labelAlign: 'right',
                            labelWidth: 50,
                            readOnly: true
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: '100%',
                    title: '用户关联设备',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: 400,
                            header: false,
                            manageHeight: false,
                            enableColumnHide: false,
                            enableColumnMove: false,
                            enableColumnResize: false,
                            forceFit: true,
                            store: 'UserEquipmentModels',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'id',
                                    text: 'ID',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'mac',
                                    text: 'My Field'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'descirption',
                                    text: 'Descirption'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'type',
                                    text: 'Type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'more1',
                                    text: 'More1'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'more2',
                                    text: 'More2'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'more3',
                                    text: 'More3'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.RowModel', {

                            })
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});