/*
 * File: app/view/User.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.User', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.grid.column.Boolean',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Date',
        'Ext.panel.Tool',
        'Ext.toolbar.Paging'
    ],

    height: 581,
    width: 849,
    layout: 'anchor',
    title: '用户详情管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 200,
                    itemId: 'AllUser',
                    padding: '10 0 0 10',
                    header: false,
                    manageHeight: false,
                    title: '用户详情管理',
                    url: 'UserAction',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: '100%',
                            title: '拥有用户',
                            layout: {
                                type: 'table',
                                columns: 3
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    padding: '0 10',
                                    fieldLabel: '用户总数',
                                    labelAlign: 'right',
                                    name: 'sum',
                                    value: '54'
                                },
                                {
                                    xtype: 'displayfield',
                                    colspan: 2,
                                    padding: '0 10',
                                    fieldLabel: '累计注册用户数',
                                    labelAlign: 'right',
                                    name: 'addtosum',
                                    value: '55'
                                },
                                {
                                    xtype: 'displayfield',
                                    padding: '0 10',
                                    fieldLabel: '今日上线用户数',
                                    name: 'activetoday',
                                    value: '10'
                                },
                                {
                                    xtype: 'displayfield',
                                    colspan: 2,
                                    padding: '0 10',
                                    fieldLabel: '今日新增用户',
                                    name: 'newer',
                                    value: '4'
                                },
                                {
                                    xtype: 'displayfield',
                                    colspan: 3,
                                    padding: '0 10',
                                    width: 225,
                                    fieldLabel: '用户累计上线总数',
                                    labelWidth: 120,
                                    name: 'addtoactive',
                                    value: '88'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'left',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'AddNewUser',
                                    text: '添加新用户'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'DeleSelectUser',
                                    text: '删除选中用户'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    anchor: '0 70%',
                    title: '',
                    items: [
                        {
                            xtype: 'gridpanel',
                            itemId: 'UserList',
                            title: '用户信息详细列表',
                            enableColumnHide: false,
                            enableColumnMove: false,
                            enableColumnResize: false,
                            forceFit: true,
                            sortableColumns: false,
                            store: 'UserModels',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    width: 80,
                                    dataIndex: 'id',
                                    text: 'ID'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 83,
                                    dataIndex: 'name',
                                    text: '名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 85,
                                    dataIndex: 'pwd',
                                    text: '密码'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 85,
                                    dataIndex: 'isonline',
                                    text: '是否在线'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'amount',
                                    text: '设备数量',
                                    format: '00'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 155,
                                    dataIndex: 'lasttime',
                                    text: '上次登录时间',
                                    format: 'Y-m-d h:m'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastip',
                                    text: '上次登录IP'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            tools: [
                                {
                                    xtype: 'tool',
                                    type: 'plus',
                                    listeners: {
                                        click: {
                                            fn: me.onTooladdClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'tool',
                                    type: 'search',
                                    listeners: {
                                        click: {
                                            fn: me.onToolsearchclick,
                                            scope: me
                                        }
                                    }
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'UserModels'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onTooladdClick: function(tool, e, eOpts) {
        Ext.create('smart.view.AddNewUser').show();
    },

    onToolsearchclick: function(tool, e, eOpts) {

        Ext.create('smart.view.User.Search').show();
    }

});