/*
 * File: app/view/User/Search.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.User.Search', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Date'
    ],

    height: 516,
    width: 835,
    layout: 'column',
    frameHeader: false,
    title: '查找用户',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    columnWidth: 0.3,
                    height: '100%',
                    bodyPadding: 10,
                    frameHeader: false,
                    header: false,
                    manageHeight: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '用户名',
                            labelWidth: 50
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '用户编号',
                            labelWidth: 60
                        },
                        {
                            xtype: 'radiogroup',
                            fieldLabel: '是否在线',
                            labelWidth: 60,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Yes'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'No'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 31,
                                    width: '100%',
                                    text: '搜索'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    columnWidth: 0.7,
                    height: '100%',
                    header: false,
                    manageHeight: false,
                    title: 'My Grid Panel',
                    forceFit: true,
                    store: 'UserModels',
                    viewConfig: {
                        border: ''
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 59,
                            dataIndex: 'id',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'pwd',
                            text: 'Pwd'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'isonline',
                            text: 'Isonline'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'lasttime',
                            text: 'Lasttime',
                            format: 'm/j/Y'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastip',
                            text: 'Lastip'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'amount',
                            text: 'Amount',
                            format: '00'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});