/*
 * File: app/controller/FirstController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.controller.FirstController', {
    extend: 'Ext.app.Controller',

    onquitClick: function(button, e, eOpts) {
        Ext.getCmp('NoticeWindow').destroy();
    },

    onNoticeQuitClick: function(button, e, eOpts) {
        button.up('window').destroy();
    },

    onNoticeGridItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var notice=Ext.create('smart.view.NoticeWindow');

        //获取新闻的详细内容
        var content='Error 404';
        Ext.Ajax.request({
            url: 'NoticeDetailAction',
            params: {
                //根据上传通知的ID获取通知的详细内容
                id: record.get('id')
            },
            success: function(response){
                content = response.responseText;
                notice.show();
                notice.queryById('NoticeTitle').update({
                'title':record.get('title'),
                'content':content,
                'time':record.get('date')
                });

            },
            failure: function(response, opts) {
                console.log('server-side failure with status code ' + response.status);
            }
        });

    },

    onSubmitAddNewsClick: function(button, e, eOpts) {
           //--获取表单
                var sform=button.up('form').getForm();
            //--添加news
             sform.submit({
                                    success: function(sform, action) {
                                      Ext.Msg.alert('Success','添加成功');
                                      button.up('window').destroy();
                                    },
                                    failure: function(sform, action) {
                                        Ext.Msg.alert('Failed','添加失败');
                                    }
                                });

    },

    onQuitAddNewsClick: function(button, e, eOpts) {
         button.up('window').destroy();
    },

    onAddNewsbtnClick: function(button, e, eOpts) {
        Ext.create('smart.view.AddNews').show();
    },

    onEditeMgrInfoClick: function(button, e, eOpts) {
        //获取已有信息
        var form=button.up('form').getForm();
        var d=form.getValues(false,false,false,true);

        //编辑管理员信息
        var edit=Ext.create('smart.view.Mgr.AddAndEdit');

        edit.down('form').getForm().setValues(d);
        edit.show();
        edit.setTitle('更改个人信息');
    },

    onListMgrsClick: function(button, e, eOpts) {
        var list=Ext.create('smart.view.Mgr.List');
        list.show();
    },

    onMgrFromBeforeRender: function(component, eOpts) {
        console.log(component);
        //获取管理员的个人信息
         Ext.Ajax.request({
                    url: 'MgrInfoAction',
                    params: {

                    },
                    success: function(response){
                        content = response.responseText;

                        //接收到的数据转化成Data对象，送给Form

                        var datejson=Ext.JSON.decode(content);
                        console.log(datejson);
                        component.getForm().setValues(datejson);

                    },
                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });

    },

    init: function(application) {
        this.control({
            "#mybutton3": {
                click: this.onquitClick
            },
            "#NoticeQuit": {
                click: this.onNoticeQuitClick
            },
            "#NoticeGrid": {
                itemdblclick: this.onNoticeGridItemDblClick
            },
            "#SubmitAddNews": {
                click: this.onSubmitAddNewsClick
            },
            "#QuitAddNews": {
                click: this.onQuitAddNewsClick
            },
            "#AddNewsbtn": {
                click: this.onAddNewsbtnClick
            },
            "#EditeMgrInfo": {
                click: this.onEditeMgrInfoClick
            },
            "#ListMgrs": {
                click: this.onListMgrsClick
            },
            "#MgrFrom": {
                beforerender: this.onMgrFromBeforeRender
            }
        });
    }

});
