/*
 * File: app/controller/MainConroller.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.controller.MainConroller', {
    extend: 'Ext.app.Controller',

    onLoginBtnClick: function(button, e, eOpts) {

        var sform = button.up('form').getForm();

                        // Submit the Ajax request and handle the response
                        sform.submit({
                            success: function(sform, action) {
                               Ext.create('smart.view.MainView').show();
                               Ext.getCmp('LoginWindow').destroy();
                            },
                            failure: function(sform, action) {
                               Ext.create('smart.view.MainView').show();
                               Ext.getCmp('LoginWindow').destroy();
                            }
                        });

    },

    onFirstClick: function(item, e, eOpts) {
        Ext.getCmp('Content').getLayout().setActiveItem(0);

    },

    onUserMgrClick: function(item, e, eOpts) {
        Ext.getCmp('Content').getLayout().setActiveItem(1);

    },

    onEquipmentMgrClick: function(item, e, eOpts) {
        Ext.getCmp('Content').getLayout().setActiveItem(2);

    },

    onSeverMgrClick: function(item, e, eOpts) {
        Ext.getCmp('Content').getLayout().setActiveItem(3);

    },

    onQuitClick: function(button, e, eOpts) {
        //-----退出程序
        Ext.getCmp('MainView').destroy();
        //--向服务器发送退出消息
                Ext.Ajax.request({
                    url: 'LoginOutAction',
                    params: {
                        //根据上传用户的ID--目前还没有存储用户的ID，所以没办法上传
                        id: record.get('id')
                    },
                    success: function(response){


                    },
                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });

        Ext.create('smart.view.Login').show();
    },

    init: function(application) {
        this.control({
            "#LoginBtn": {
                click: this.onLoginBtnClick
            },
            "#First": {
                click: this.onFirstClick
            },
            "#UserMgr": {
                click: this.onUserMgrClick
            },
            "#EquipmentMgr": {
                click: this.onEquipmentMgrClick
            },
            "#SeverMgr": {
                click: this.onSeverMgrClick
            },
            "#Quit": {
                click: this.onQuitClick
            }
        });
    }

});
