/*
 * File: app/controller/SeverController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.controller.SeverController', {
    extend: 'Ext.app.Controller',

    onSeverInfoAfterRender: function(component, eOpts) {
        //加载服务器基本信息

         Ext.Ajax.request({
                    url: 'SeverInfoAction',
                    params: {

                    },
                    success: function(response){
                        content = response.responseText;

                        //接收到的数据转化成Data对象，送给Form

                        var datejson=Ext.JSON.decode(content);
                        console.log(datejson);
                        component.getForm().setValues(datejson);

                    },
                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });

    },

    onSeverClusterInfoAfterRender: function(component, eOpts) {
        //加载服务器集群的基本信息

         Ext.Ajax.request({
                    url: 'SeverClusterInfoAction',
                    params: {

                    },
                    success: function(response){
                        content = response.responseText;

                        //接收到的数据转化成Data对象，送给Form

                        var datejson=Ext.JSON.decode(content);
                        console.log(datejson);
                        component.getForm().setValues(datejson);

                    },
                    failure: function(response, opts) {
                        console.log('server-side failure with status code ' + response.status);
                    }
                });
    },

    init: function(application) {
        this.control({
            "#SeverInfo": {
                afterrender: this.onSeverInfoAfterRender
            },
            "#SeverClusterInfo": {
                afterrender: this.onSeverClusterInfoAfterRender
            }
        });
    }

});
