/*
 * File: app/view/Mgr/AddAndEdit.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.Mgr.AddAndEdit', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 395,
    width: 348,
    layout: 'fit',
    title: '添加管理员',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: '10 30 10 0',
                    header: false,
                    title: 'My Form',
                    url: 'AddMgrAction',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: '编号',
                            labelAlign: 'right',
                            name: 'num',
                            value: '0075'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'ID',
                            labelAlign: 'right',
                            name: 'id',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '昵称',
                            labelAlign: 'right',
                            name: 'nickname',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '姓名',
                            labelAlign: 'right',
                            name: 'name',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '电话',
                            labelAlign: 'right',
                            name: 'tel',
                            inputType: 'tel',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Email',
                            labelAlign: 'right',
                            name: 'email',
                            inputType: 'email',
                            allowBlank: false
                        },
                        {
                            xtype: 'radiogroup',
                            fieldLabel: '性别',
                            labelAlign: 'right',
                            allowBlank: false,
                            layout: {
                                type: 'checkboxgroup',
                                autoFlex: false
                            },
                            items: [
                                {
                                    xtype: 'radiofield',
                                    padding: '0 30 0 0',
                                    value: 'man',
                                    boxLabel: '男',
                                    checked: true
                                },
                                {
                                    xtype: 'radiofield',
                                    value: 'woman',
                                    boxLabel: '女'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '密码',
                            labelAlign: 'right',
                            inputType: 'password',
                            allowBlank: false,
                            vtype: ''
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '重复输入密码',
                            labelAlign: 'right',
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '级别',
                            labelAlign: 'right',
                            name: 'type',
                            allowBlank: false
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            formBind: true,
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    style: 'border:1px solid #006699',
                                    width: 100,
                                    text: '确认'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});