/*
 * File: app/view/Mgr/List.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('smart.view.Mgr.List', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.View',
        'Ext.panel.Tool',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date'
    ],

    height: 510,
    width: 702,
    frameHeader: false,
    header: false,
    title: '管理员列表',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    title: '所有管理元列表',
                    columnLines: false,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    enableColumnResize: false,
                    forceFit: true,
                    sortableColumns: false,
                    store: 'MgrLists',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 47,
                            text: '序号'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 66,
                            dataIndex: 'num',
                            text: '编号',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 62,
                            dataIndex: 'id',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 86,
                            dataIndex: 'name',
                            text: '姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 88,
                            dataIndex: 'type',
                            text: '权限'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastip',
                            text: '上次登录IP'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'updatetime',
                            text: '上次登录时间',
                            format: 'd-m-Y'
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            itemId: 'AddMgr',
                            type: 'plus',
                            listeners: {
                                click: {
                                    fn: me.onAddMgrClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tool',
                            type: 'close',
                            listeners: {
                                click: {
                                    fn: me.onToolClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onAddMgrClick: function(tool, e, eOpts) {
        //添加新的管理员
        var addmgr=Ext.create('smart.view.Mgr.AddAndEdit');
        addmgr.show();
    },

    onToolClick: function(tool, e, eOpts) {
        //关闭按钮
        tool.up('window').destroy();
    }

});